In [1]:
import numpy as np

In [3]:
arr=np.array(range(2,51,3))
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [8]:
arr1=[]
for i in range(0,5):
    a=int(input())
    arr1.append(a)
arr2=[]
for i in range(0,5):
    b=int(input())
    arr2.append(b)
arr1=np.array(arr1)
arr2=np.array(arr2)
arr3=np.concatenate((arr1,arr2), axis=0)
print(arr3)
print(np.sort(arr3))

9
8
7
6
5
4
3
2
1
0
[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
# CODE SNIPPET FOR FINDING THE DIRECTION OF NDARRAY IS : array_name.ndim
# CODE SNIPPET FOR FINDING THE SHAPE  OF ARRAY IS : array_name.shape
arr=np.array([[1,2,3],[3,4,5]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [3 4 5]]
2
(2, 3)


In [12]:
import numpy as np
arr=np.array([1,2,3])
print(arr.shape)
arr1=arr[:,np.newaxis]  #1
print(arr1.shape)
arr2=np.expand_dims(arr, axis=0)  #2
print(arr2.shape)

(3,)
(3, 1)
(1, 3)


In [9]:
import numpy as np
arr=np.array([[1,1],[1,1]])
arr1=np.array([[2,2],[2,2]])
np.vstack((arr,arr1))

array([[1, 1],
       [1, 1],
       [2, 2],
       [2, 2]])

In [10]:
arr=np.array([[1,1],[1,1]])
arr1=np.array([[2,2],[2,2]])
np.hstack((arr,arr1))

array([[1, 1, 2, 2],
       [1, 1, 2, 2]])

In [12]:
arr=np.array([1,2,3,3,2,2,1,3,34,4,5,334,23,23,23,5,5,4,5,6,7,5])
arr
uniquevalues,count=np.unique(arr,return_counts=True)
print('Unique values are :',uniquevalues)
print('count is :',count)

Unique values are : [  1   2   3   4   5   6   7  23  34 334]
count is : [2 3 3 2 5 1 1 3 1 1]
